### ISSUE TITLE
trace_interrupt() is not working for busy traffic.

### ISSUE THREAD

**Issue by EaseTheWorld** [wanduow/libtrace#36] opened 2016-11-17 00:22 UTC
in each format_xxx.c, libtrace_halt is checked in timeout case.
but when traffic is busy, timeout is not occured so interrupt() doesn't work.
Easy fix would be move out libtrace_halt check to the first line in the read loop
but is there any intentional reason not to? (volatile int read performance? I don't know.)

**Comment by rsanger** [comment] 2016-11-17 22:48
Traditionally [programs](https://github.com/wanduow/libtrace/blob/master/tools/tracemerge/tracemerge.c#L54-L60) have used an extra flag in their signal handler and checked this before reading a packet. Trace_interrupt() was added to allow an application to break in the case a live format was not receiving any packets.

But, I think this is mainly based on how things have always been done, and as you say I think it makes sense for libtrace to check this in its read loop. I don't think the read performance should suffer significantly. I will look into this more and figure out the best place to put this to handle cases such as filtering correctly.

PS: If you are using the parallel API, trace_pstop() replaces trace_interrupt() as this allows you to stop an individual trace rather than it applying globally to all open traces.

**Comment by EaseTheWorld** [comment] 2016-11-17 23:08
Thank you for consider this. And about pstop, I've been using both parallel api(onlyif trace_is_parallel() is true) and simple api(main for pcap file and dirs).

**Comment by rsanger** [comment] 2016-11-17 23:40
You don't need to use the two code paths for this. The parallel api will work in cases trace_is_parallel(). Trace_is_parallel() indicates the underlying format can produce parallel streams of packets, such as using multiple queues on a NIC.

You have two options, depending on your work load.
1). If your workload is low per packet - limit the trace to using a single thread trace_set_perpkt_threads(trace, 1) - this incurs only a small overhead compared to the single threaded API.
2). If your per packet workload is high then multiple threads might be useful and the default behaviour will create perpkt threads matching the number of processors. However this does incur an additional performance penalty as libtrace internally splits these packets between threads.

**Comment by EaseTheWorld** [comment] 2016-11-18 04:26
You are right. Actually I'm using 3 types.
1. for dpdk, parallel api with 8 perpkt threads.
2. for ring and pcapint, parallel api with 1 perpkt thread.
    I tried ring with 8 thread, but then trace_pstop() doesn't work well...
    maybe race condition somewhere.
3. for pcap files, simple api.

**Comment by rsanger** [comment] 2016-11-24 22:50
This should be fixed now in the [develop](https://github.com/wanduow/libtrace/tree/develop) branch.

I'm not sure what the problem is with ring not working well with trace_pstop(), I could not replicate this. 
Would you mind checking if you see this same behaviour with trace_pstop() and tracestats. If so log it as another issue as it sounds like a bug.

**Closed by rsanger** 2016-11-24 22:50 UTC

**Comment by EaseTheWorld** [comment] 2016-11-29 04:12
Verified. I tested ring, int, pcapint, dpdk.
