### ISSUE TITLE
trace_pstop() doesn't work with ring and many perpkt threads

### ISSUE THREAD

**Issue by EaseTheWorld** [wanduow/libtrace#39] opened 2016-11-29 02:27 UTC
I connected 2 workstations directly.
1 sends traffic with pktgen-dpdk and 1 receives with tracestats with threads.

A) When I press Ctrl+C, tracestats(8threads) doesn't stop. if I use 1 thread, trace_pstop() works well.

B) Another scenario is tracestats with no traffic.(absolutely no packet), trace_pstop() doesn't work.

**Comment by rsanger** [comment] 2016-12-01 05:18
Thanks for the report.

However, I still cannot reproduce this in either scenario: under-load or unloaded.
Even with an excessive numbers of threads 100+ it still returns, although does take a bit longer maybe 5 or so seconds.

I'm guessing this might by related to a specific kernel or distribution compiler. The system I have been testing on is a Debian Jessie install with the 3.16.36-1+deb8u2 kernel, with 8 64-bit Intel cores. Using a build of the libtrace develop branch. 

Sorry for the hassle but can I get some more info:
1. Double check you are using the development branch of libtrace and this is being run, put a print in the code to confirm (say in trace_create).
2. Any additional compile flags that you are using (or modifications), outside of what `./configure; make install` would give you
3. Is this an issue with only ring: or int: also?
4. CPU model and core count
5. Linux distribution and kernel version
6. If possible, gdb output would be useful in scenario B. The output of `thread apply all bt full` is of interest during the hang as this shows where threads are stuck (example below) and a copy of the core file.

```
sudo gdb --args tracestats --threads 8 ring:eth0
...
(gdb) run
...
<Wait a couple of seconds and hit Ctrl+C>
(gdb) signal 2  <--- this sends a SIGINT
Continuing with signal SIGINT.
<Wait a couple of seconds and hit Ctrl+C>
(gdb) thread apply all bt full
Thread 10 (Thread 0x7fffef89c700 (LWP 18022)):
...
(gdb) generate-core-file
Saved corefile core.18026
(gdb) quit
```

Thanks

**Comment by EaseTheWorld** [comment] 2016-12-02 00:32
Your guess was right. Issue reproduced in RHEL6. No issue in RHEL7.
Detail : RHEL6.7(kernel 2.6.32-673.el6.x86_64), gcc 4.9.2
Xeon E5-1680 v2 3GHz. 8 core(16 hyperthread)

I built with ./configure --without-ncurse && make

issue in ring only. no issue in int.

I cannot post core file so I will type some of gdb result
(issue is reproduced less often on gdb)

Thread 4
    read() from /lib64/libpthread.so.0
    libtrace_message_queue_get(mq=...)
    reporter_entry
Thread 3
    poll() from /lib64/libc.so.6
    linuxring_read_stream(queue=0x0, ...)
    trace_read_packet()
    trace_pread_packet_first_in_first_served
    perpkt_threads_entry
Thread 2
    _lll_lock_wait() from /lib64/libpthread.so.0
    _L_lock_854()
    pthread_mutex_lock()
    trace_fin_packet()
    dispatch_packet()
    perpkt_threads_entry
Thread 1
    _lll_lock_wait() from /lib64/libpthread.so.0
    _L_lock_854()
    pthread_mutex_lock()
    trace_ppause()
    trace_pstop()
    pthread_join()
    trace_join()

**Comment by rsanger** [comment] 2016-12-05 06:25
Hopefully the commit 5e3f16c on the develop branch should fix the issue.

I was able to replicate in a VM in the no packet case and this patch seems to fix the problem for me. It seemed to affect both the int and ring formats not just the ring.
However did not have the chance to test at high packet rates, but I would expect this to be fixed now too.

Let me know if this has solved the problem. Thanks

**Comment by EaseTheWorld** [comment] 2016-12-06 01:01
HAVE_PACKET_FANOUT is undefined as you guessed.(RHEL6.7)
With commit 5e3f16c no packet case is fixed because main thread and perpkt thread uses different lock now but high rate case, 2 perpkt threads wait for read_packet_lock.
It seems moving is_halt() the first of while-poll loop fixed the issue.

Thread 3
poll()
linuxring_read_stream() at format_linux_ring.c:482
trace_pread_packet_first_in_first_served() at trace_parallel.c:891
Thread 2
trace_pread_packet_first_in_first_served() at trace_parallel.c:902



I used two machines. one running "tracestats -t 2 ring:eth1".
another running "tcpreplay -l 0 -t -i ens3f1 sample.pcap"

**Comment by rsanger** [comment] 2016-12-06 01:28
Just to double check this has fully solved both issues and can be closed now?

**Comment by EaseTheWorld** [comment] 2016-12-06 04:29
No. Maybe you missed my comment above.

**Comment by EaseTheWorld** [comment] 2016-12-12 01:18
When working normally, header->tp_status 0..5..13(TP_STATUS_USER flag is on and off).
When halt is not working, header->tp_status is always 0 and pollset[0].revents is POLLIN so halt check code is never executed.
To fix this, move halt check to the first line in while(!(tp_status&TP_STATUS_USER), or
find out why tp_status is always 0 when traffic is busy.

**Comment by rsanger** [comment] 2016-12-15 04:30
Sorry for the delay and thank you for the additional information.

I was able to replicate the problem and I believe 47c4490 should fix it.
This was a number of smaller issues for all the details see the commit message.

Let me know if this has fixed all the problems now.
Thanks

**Comment by EaseTheWorld** [comment] 2016-12-15 23:44
The issue is fixed. Thank you. I can move on to next commit~

**Closed** 2016-12-16 00:28 UTC
